// Seed data for INSTAGRAM in Mock Mode

export const SEED_USERS = [
  {
    uid: "osh_admin",
    username: "osh_admin",
    displayName: "Admin INSTAGRAM",
    email: "admin@bloggerosh.kg",
    phone: "+996555112233",
    bio: "Официальный аккаунт администратора INSTAGRAM. Управление контентом и пользователями",
    photoURL: "https://api.dicebear.com/7.x/avataaars/svg?seed=osh_admin&backgroundColor=b6e3f4",
    coverURL: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
    followers: ["traveler_osh", "photo_kg", "reels_star"],
    following: ["traveler_osh"],
    blockedUsers: [],
    isPrivate: false,
    isAdmin: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() // 30 days ago
  },
  {
    uid: "traveler_osh",
    username: "traveler_osh",
    displayName: "Эркин Путешественник",
    email: "traveler@bloggerosh.kg",
    phone: "+996777445566",
    bio: "Показываю самые красивые уголки города Ош и Кыргызстана. Горы Сулайман-Тоо — моя любовь! 🏔️✈️",
    photoURL: "https://api.dicebear.com/7.x/avataaars/svg?seed=traveler_osh&backgroundColor=ffdfbf",
    coverURL: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=1200&auto=format&fit=crop&q=80",
    followers: ["osh_admin", "reels_star"],
    following: ["osh_admin", "photo_kg", "reels_star"],
    blockedUsers: [],
    isPrivate: false,
    isAdmin: false,
    createdAt: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    uid: "photo_kg",
    username: "photo_kg",
    displayName: "Айбек Фотограф",
    email: "photo@bloggerosh.kg",
    phone: "+996500889900",
    bio: "Профессиональная съемка в Оше. Портреты, свадьбы, мобилография. Пишите в Direct! 📸✨",
    photoURL: "https://api.dicebear.com/7.x/avataaars/svg?seed=photo_kg&backgroundColor=d1f4ff",
    coverURL: "https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=1200&auto=format&fit=crop&q=80",
    followers: ["traveler_osh"],
    following: ["traveler_osh", "reels_star"],
    blockedUsers: [],
    isPrivate: false,
    isAdmin: false,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    uid: "reels_star",
    username: "reels_star",
    displayName: "Адинай Видеомейкер",
    email: "reels@bloggerosh.kg",
    phone: "+996999334455",
    bio: "Создаю вирусные Reels. Тренды, юмор, эстетика Оша. Коллаборации в ЛС! 🎬🔥",
    photoURL: "https://api.dicebear.com/7.x/avataaars/svg?seed=reels_star&backgroundColor=ffd5dc",
    coverURL: "https://images.unsplash.com/photo-1557683316-973673baf926?w=1200&auto=format&fit=crop&q=80",
    followers: ["traveler_osh", "photo_kg"],
    following: ["traveler_osh"],
    blockedUsers: [],
    isPrivate: false,
    isAdmin: false,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    uid: "akaktish",
    username: "akaktish",
    displayName: "Стоматология АКАК ТИШ",
    email: "info@akaktish.kg",
    phone: "+996555700011",
    bio: "Премиальная стоматологическая клиника в г. Ош 🦷✨ Имплантация, брекеты, отбеливание и безболезненное лечение зубов! Запишитесь онлайн 👇",
    photoURL: "https://api.dicebear.com/7.x/bottts/svg?seed=akaktish&backgroundColor=c0f2fe",
    coverURL: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=1200&auto=format&fit=crop&q=80",
    followers: ["traveler_osh", "photo_kg", "reels_star", "osh_admin"],
    following: [],
    blockedUsers: [],
    isPrivate: false,
    isAdmin: false,
    isVerified: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    uid: "cartoon_master",
    username: "cartoon_master",
    displayName: "Мульт Мастер 🎬",
    email: "cartoon@bloggerosh.kg",
    phone: "+996500707070",
    bio: "Создаю яркие 3D мультфильмы и концепт-арты! Подпишись, чтобы не пропустить новые серии! 🐱🚀",
    photoURL: "https://api.dicebear.com/7.x/avataaars/svg?seed=cartoon_master&backgroundColor=d1f4ff",
    coverURL: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80",
    followers: ["traveler_osh", "reels_star"],
    following: [],
    blockedUsers: [],
    isPrivate: false,
    isAdmin: false,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    uid: "vlad_a4",
    username: "a4omg",
    displayName: "Влад А4",
    email: "vlad@a4.ru",
    phone: "+996555443322",
    bio: "Официальный аккаунт А4! ⚡ Новые челленджи, крутые видосы и мерч! Подписывайся! 🕶️🔥",
    photoURL: "https://api.dicebear.com/7.x/avataaars/svg?seed=vladA4&backgroundColor=ffd5dc",
    coverURL: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&auto=format&fit=crop&q=80",
    followers: ["traveler_osh", "photo_kg", "reels_star", "osh_admin"],
    following: [],
    blockedUsers: [],
    isPrivate: false,
    isAdmin: false,
    isVerified: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    uid: "masha_medved",
    username: "masha_and_bear",
    displayName: "Маша и Медведь 👧🐻",
    email: "masha@mashabear.ru",
    phone: "+996555778899",
    bio: "Официальный канал мультсериала «Маша и Медведь»! 👧🎈🐻 Все самые любимые серии, песни и приключения!",
    photoURL: "https://api.dicebear.com/7.x/bottts/svg?seed=masha_medved&backgroundColor=ffd5dc",
    coverURL: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1200&auto=format&fit=crop&q=80",
    followers: ["traveler_osh", "photo_kg", "reels_star", "osh_admin", "cartoon_master"],
    following: [],
    blockedUsers: [],
    isPrivate: false,
    isAdmin: false,
    isVerified: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString()
  }
];

export const SEED_POSTS = [
  {
    id: "post_a4_1",
    userId: "vlad_a4",
    type: "video",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    caption: "1,000 ЗАДАНИЙ за 24 ЧАСА ЧЕЛЛЕНДЖ ! 😱 Наш самый новый и безумный выпуск! Смотри прямо сейчас 👇 #a4 #challenge #omg #fun #vlad",
    hashtags: ["a4", "challenge", "omg", "fun", "vlad"],
    likes: ["traveler_osh", "reels_star", "photo_kg", "osh_admin"],
    saves: ["vlad_a4"],
    commentsCount: 3,
    viewsCount: 1540,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "post_a4_2",
    userId: "vlad_a4",
    type: "photo",
    mediaURL: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80",
    caption: "Новый фирменный мерч А4 уже доступен! 🎒⚡ Какая футболка круче: оранжевая или зеленая? #a4merch #style #a4",
    hashtags: ["a4merch", "style", "a4"],
    likes: ["traveler_osh", "reels_star"],
    saves: [],
    commentsCount: 2,
    viewsCount: 920,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "post_cartoon_1",
    userId: "cartoon_master",
    type: "photo",
    mediaURL: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    caption: "Премьера новой серии мультфильма 'Приключения в городе Ош'! 🎬🍿 Напишите в комментариях, какой ваш любимый персонаж! #cartoon #animation #anime #osh #art #fun",
    hashtags: ["cartoon", "animation", "anime", "osh", "art", "fun"],
    likes: ["traveler_osh", "reels_star", "photo_kg", "osh_admin"],
    saves: ["cartoon_master"],
    commentsCount: 4,
    viewsCount: 1540,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "post_cartoon_2",
    userId: "cartoon_master",
    type: "photo",
    mediaURL: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80",
    caption: "Концепт-арт к аниме-сериалу в стиле студии Ghibli. Закат на фоне гор. 🎨✨ #anime #ghibli #cartoon #art #sketch",
    hashtags: ["anime", "ghibli", "cartoon", "art", "sketch"],
    likes: ["traveler_osh", "reels_star"],
    saves: ["traveler_osh"],
    commentsCount: 2,
    viewsCount: 920,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "post_1",
    userId: "traveler_osh",
    type: "photo",
    mediaURL: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80",
    caption: "Сулайман-Тоо на закате. Вид, от которого захватывает дух. Согласны? 😍 #osh #sulaimantoo #kyrgyzstan #travel #sunset",
    hashtags: ["osh", "sulaimantoo", "kyrgyzstan", "travel", "sunset"],
    likes: ["osh_admin", "photo_kg", "reels_star"],
    saves: ["osh_admin"],
    commentsCount: 2,
    viewsCount: 450,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "post_2",
    userId: "photo_kg",
    type: "photo",
    mediaURL: "https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80",
    caption: "Новая атмосфера съемок на объектив 85mm f/1.4. Детализация портрета на высоте! 📸✨ #photo #portrait #aesthetic #osh",
    hashtags: ["photo", "portrait", "aesthetic", "osh"],
    likes: ["traveler_osh", "reels_star"],
    saves: [],
    commentsCount: 1,
    viewsCount: 289,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "post_3",
    userId: "traveler_osh",
    type: "photo",
    mediaURL: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&auto=format&fit=crop&q=80",
    caption: "А вы знали, что настоящий ошский плов готовится на узгенском рисе «девзира»? Аромат на всю чайхану! 🍛🤤 #plov #oshfood #traditional #yummy",
    hashtags: ["plov", "oshfood", "traditional", "yummy"],
    likes: ["osh_admin", "photo_kg", "reels_star"],
    saves: ["traveler_osh"],
    commentsCount: 2,
    viewsCount: 610,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "post_4",
    userId: "reels_star",
    type: "photo",
    mediaURL: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=800&auto=format&fit=crop&q=80",
    caption: "Утренняя музыкальная пауза. Записываем новый трек для следующего вирусного видео Reels! 🎶🔥 #music #studio #beats #reels #osh",
    hashtags: ["music", "studio", "beats", "reels", "osh"],
    likes: ["traveler_osh", "photo_kg"],
    saves: ["reels_star"],
    commentsCount: 3,
    viewsCount: 380,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "post_5",
    userId: "osh_admin",
    type: "photo",
    mediaURL: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800&auto=format&fit=crop&q=80",
    caption: "Вечерний уют в лучших заведениях южной столицы. Город Ош развивается с каждым днём! ☕✨ #bloggerosh #citylife #osh2026",
    hashtags: ["bloggerosh", "citylife", "osh2026"],
    likes: ["traveler_osh", "reels_star", "photo_kg"],
    saves: ["osh_admin"],
    commentsCount: 1,
    viewsCount: 820,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString()
  }
];

export const SEED_REELS = [
  {
    id: "reel_masha_1",
    userId: "masha_medved",
    type: "reel",
    mediaURL: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    coverURL: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    caption: "👧🐻 Маша и Медведь - «День Варенья»! 🍓🍯 Забавные приключения Маши в волшебном лесу!🍿 #машаимедведь #мультики #masha #kids",
    hashtags: ["машаимедведь", "мультики", "masha", "kids"],
    audioTitle: "🎵 Маша и Медведь — Песенка про Варенье 🍓🎈",
    likes: ["traveler_osh", "photo_kg", "reels_star", "osh_admin"],
    saves: ["masha_medved"],
    viewsCount: 28490,
    commentsCount: 35,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date().toISOString()
  },
  {
    id: "reel_masha_2",
    userId: "masha_medved",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    coverURL: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
    caption: "👧🎈 Маша и Медведь - «Большая Стирка»! 🧼💦 Смотрите оригинальную серию прямо тут! #машаимедведь #мультики #masha #funny",
    hashtags: ["машаимедведь", "мультики", "masha", "funny"],
    audioTitle: "🎵 Маша и Медведь — Большая Стирка (Саундтрек) 🧼💦",
    likes: ["traveler_osh", "reels_star", "osh_admin"],
    saves: [],
    viewsCount: 19800,
    commentsCount: 24,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString()
  },
  {
    id: "reel_masha_3",
    userId: "masha_medved",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    coverURL: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=800&auto=format&fit=crop&q=80",
    caption: "👧🐾 Маша и Медведь - «Следы невиданных зверей»! 🐻👣 Веселые расследования Маши! #машаимедведь #мультики #cartoons",
    hashtags: ["машаимедведь", "мультики", "cartoons"],
    audioTitle: "🎵 Маша и Медведь — Следы Невиданных Зверей 🐾🐻",
    likes: ["photo_kg", "reels_star"],
    saves: ["masha_medved"],
    viewsCount: 22100,
    commentsCount: 18,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString()
  },
  {
    id: "reel_a4_1",
    userId: "vlad_a4",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    coverURL: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80",
    caption: "1,000 ЗАДАНИЙ за 24 ЧАСА ЧЕЛЛЕНДЖ ! 😱 Наш самый взрывной выпуск А4! Смотри прямо тут 👇 #a4 #challenge #24hours",
    hashtags: ["a4", "challenge", "24hours"],
    audioTitle: "🎵 Влад А4 — 1,000 Заданий 24 Часа (Официальный Бит) ⚡🔥",
    likes: ["traveler_osh", "photo_kg", "reels_star", "osh_admin"],
    saves: ["vlad_a4"],
    viewsCount: 15420,
    commentsCount: 22,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString()
  },
  {
    id: "reel_a4_2",
    userId: "vlad_a4",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
    coverURL: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80",
    caption: "100 СЛОЕВ ЕДЫ ЧЕЛЛЕНДЖ ! 🍔🌭 Кто съест больше всего — побеждает! #a4 #challenge #food #fun",
    hashtags: ["a4", "challenge", "food", "fun"],
    audioTitle: "🎵 Влад А4 — 100 Слоев Еды Челлендж 🍔🌭",
    likes: ["reels_star", "photo_kg"],
    saves: [],
    viewsCount: 12890,
    commentsCount: 14,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_a4_3",
    userId: "vlad_a4",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
    coverURL: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=800&auto=format&fit=crop&q=80",
    caption: "ПОБЕГ ИЗ САМОЙ СТРОГОЙ ТЮРЬМЫ ЗА 24 ЧАСА ! 🚨🔓 Сбежали ли мы от охранников? #a4 #jailbreak #escape #vlad",
    hashtags: ["a4", "jailbreak", "escape", "vlad"],
    audioTitle: "🎵 A4 Production — Побег из Тюрьмы Экшен Бит 🚨🔓",
    likes: ["traveler_osh", "reels_star", "osh_admin"],
    saves: ["vlad_a4"],
    viewsCount: 9410,
    commentsCount: 8,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_a4_4",
    userId: "vlad_a4",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    coverURL: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&auto=format&fit=crop&q=80",
    caption: "ПОЛ ЭТО ЛАВА В РЕАЛЬНОЙ ЖИЗНИ ! 🌋🔥 Кто коснется пола — выбывает из игры! #a4 #lava #challenge #vlad",
    hashtags: ["a4", "lava", "challenge", "vlad"],
    audioTitle: "🎵 Влад А4 — Пол Это Лава Ремикс 🌋🔊",
    likes: ["traveler_osh", "photo_kg", "reels_star"],
    saves: [],
    viewsCount: 18200,
    commentsCount: 29,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_a4_5",
    userId: "vlad_a4",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
    coverURL: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80",
    caption: "УГАДАЙ СОК ПО ВКУСУ ЧЕЛЛЕНДЖ ! 🧃👅 Кто ошибся — выполняет с закрытыми глазами! #a4 #challenge #vlad",
    hashtags: ["a4", "challenge", "vlad"],
    audioTitle: "🎵 Влад А4 — Угадай Сок По Вкусу 🧃👅",
    likes: ["reels_star", "osh_admin"],
    saves: [],
    viewsCount: 21300,
    commentsCount: 34,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_cartoon_1",
    userId: "cartoon_master",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    coverURL: "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80",
    caption: "🍿 3D Мультфильм: Приключения в мире Minecraft! Эпическая битвы анимации ⚔️🟩 #cartoon #мультики #minecraft #3d #kids",
    hashtags: ["cartoon", "мультики", "minecraft", "3d", "kids"],
    audioTitle: "🎵 Minecraft 3D Animation — Dubstep Remix 🟩⚔️",
    likes: ["traveler_osh", "photo_kg", "reels_star", "osh_admin"],
    saves: ["traveler_osh"],
    viewsCount: 5890,
    commentsCount: 12,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString()
  },
  {
    id: "reel_cartoon_2",
    userId: "cartoon_master",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    coverURL: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80",
    caption: "🐱🐭 Том и Джерри — ЛУЧШИЕ МОМЕНТЫ! Классика легендарных мультиков! 🍿✨ #cartoon #мультики #tomandjerry #funny",
    hashtags: ["cartoon", "мультики", "tomandjerry", "funny"],
    audioTitle: "🎵 Том и Джерри — Classic Cartoon Jazz 🎷🐱",
    likes: ["reels_star", "photo_kg", "osh_admin"],
    saves: [],
    viewsCount: 7120,
    commentsCount: 9,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_cartoon_3",
    userId: "cartoon_master",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4",
    coverURL: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80",
    caption: "🧽 Спанч Боб и Патрик — Веселье в Красти Краб! 🍔💛 #cartoon #мультики #spongebob #animation",
    hashtags: ["cartoon", "мультики", "spongebob", "animation"],
    audioTitle: "🎵 SpongeBob — Fun Song Beach Party 🧽🍔",
    likes: ["traveler_osh", "reels_star"],
    saves: ["cartoon_master"],
    viewsCount: 4390,
    commentsCount: 7,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_cartoon_7",
    userId: "cartoon_master",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4",
    coverURL: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    caption: "🐼 Кунг-Фу Панда По — Веселая битва за пельмешки! 🥟🥋 #cartoon #kungfupanda #funny #animation",
    hashtags: ["cartoon", "kungfupanda", "funny", "animation"],
    audioTitle: "🎵 Kung Fu Panda — Dragon Warrior Epic Theme 🥟🥋",
    likes: ["reels_star", "photo_kg", "osh_admin"],
    saves: [],
    viewsCount: 16500,
    commentsCount: 28,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_cartoon_8",
    userId: "cartoon_master",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4",
    coverURL: "https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80",
    caption: "🐿️ Ледниковый Период — Белка Скрат и Желудь! 🌰❄️ Самые смешные моменты! #cartoon #iceage #scrat #funny",
    hashtags: ["cartoon", "iceage", "scrat", "funny"],
    audioTitle: "🎵 Ice Age — Scrat Acorn Madness Theme 🌰❄️",
    likes: ["traveler_osh", "photo_kg"],
    saves: ["cartoon_master"],
    viewsCount: 29800,
    commentsCount: 41,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_supercar_1",
    userId: "reels_star",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackOnStreetAndDirt.mp4",
    coverURL: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80",
    caption: "Bugatti Chiron против Болида Формулы-1! 🏎️💨 Драг-рейсинг 1500 л.с.! Звук выхлопа 🔥 #supercar #bugatti #speed #cars",
    hashtags: ["supercar", "bugatti", "speed", "cars"],
    audioTitle: "🎵 Bugatti Chiron 1500 HP — V16 Engine Exhaust Sound 🏎️💨",
    likes: ["traveler_osh", "photo_kg", "osh_admin"],
    saves: ["reels_star"],
    viewsCount: 14200,
    commentsCount: 19,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_supercar_2",
    userId: "reels_star",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WhatCarCanYouGetForAGrand.mp4",
    coverURL: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80",
    caption: "Ралли и Дрифт по бездорожью! 🚗💨 Разгон до 100 км/ч за 3 секунды! #rally #drift #subaru #cars",
    hashtags: ["rally", "drift", "subaru", "cars"],
    audioTitle: "🎵 Drift Phonk — Tokyo Drift Remix 🚗🔥",
    likes: ["traveler_osh", "photo_kg"],
    saves: [],
    viewsCount: 9500,
    commentsCount: 8,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_supercar_3",
    userId: "reels_star",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4",
    coverURL: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&auto=format&fit=crop&q=80",
    caption: "BMW M5 F90 — Ночной Дрифт по городу! 🌃🏎️ 800 лошадей под капотом! #bmw #m5 #drift #cars",
    hashtags: ["bmw", "m5", "drift", "cars"],
    audioTitle: "🎵 BMW M5 F90 — Night City Drive Synthwave 🌃🏎️",
    likes: ["traveler_osh", "photo_kg", "osh_admin"],
    saves: ["reels_star"],
    viewsCount: 38200,
    commentsCount: 54,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_sports_1",
    userId: "reels_star",
    type: "reel",
    mediaURL: "youtube:E_g9KkIeZ_E",
    coverURL: "https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80",
    caption: "⚽ ФУТБОЛ 4K! Лионель Месси — Невероятные финты и дриблинг 4K! ⚽🐐 Гений мирового футбола! #футбол #фудбол #messi #football #sport #skills #гол",
    hashtags: ["футбол", "фудбол", "messi", "football", "sport", "skills", "гол"],
    audioTitle: "🎵 Lionel Messi — Magic Dribbling & Skills 4K ⚽🐐",
    likes: ["traveler_osh", "photo_kg", "reels_star", "osh_admin"],
    saves: ["reels_star"],
    viewsCount: 42100,
    commentsCount: 63,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_sports_2",
    userId: "reels_star",
    type: "reel",
    mediaURL: "youtube:34Na4j8AVgA",
    coverURL: "https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=800&auto=format&fit=crop&q=80",
    caption: "⚽ ФУТБОЛ! Криштиану Роналду — Лучшие голы и фирменное SIUUU! ⚽🔥 #футбол #фудбол #ronaldo #cr7 #football #sport #гол",
    hashtags: ["футбол", "фудбол", "ronaldo", "cr7", "football", "sport", "гол"],
    audioTitle: "🎵 Cristiano Ronaldo — SIUUU Anthem Remix ⚽🔥",
    likes: ["traveler_osh", "photo_kg", "osh_admin"],
    saves: [],
    viewsCount: 38900,
    commentsCount: 51,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_sports_3",
    userId: "reels_star",
    type: "reel",
    mediaURL: "youtube:8B6h3Y1W4Q0",
    coverURL: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
    caption: "⚽ ФУТБОЛ Лига Чемпионов! Сумасшедший красивый гол с 30 метров через себя! 😱💥 #футбол #фудбол #championsleague #football #goal",
    hashtags: ["футбол", "фудбол", "championsleague", "football", "goal"],
    audioTitle: "🎵 UEFA Champions League — Official Hymn 🏆",
    likes: ["traveler_osh", "photo_kg", "osh_admin", "reels_star"],
    saves: ["reels_star"],
    viewsCount: 54100,
    commentsCount: 78,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_nature_1",
    userId: "traveler_osh",
    type: "reel",
    mediaURL: "https://vjs.zencdn.net/v/oceans.mp4",
    coverURL: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80",
    caption: "Невероятный подводный мир океана! 🐬🌊 Дельфины и скаты в синих глубинах 💙 #ocean #dolphins #nature #underwater",
    hashtags: ["ocean", "dolphins", "nature", "underwater"],
    audioTitle: "🎵 Ocean Waves & Dolphin Chillout Symphony 🐬🌊",
    likes: ["photo_kg", "reels_star", "osh_admin"],
    saves: ["traveler_osh"],
    viewsCount: 24500,
    commentsCount: 31,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_nature_2",
    userId: "traveler_osh",
    type: "reel",
    mediaURL: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    coverURL: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
    caption: "Утренний расцвет альпийских цветов 🌸🏔️ Горы Кыргызстана под лучами солнца! #nature #flowers #kyrgyzstan",
    hashtags: ["nature", "flowers", "kyrgyzstan"],
    audioTitle: "🎵 Kyrgyzstan Mountain Morning Acoustic Guitar 🌸🏔️",
    likes: ["reels_star", "photo_kg"],
    saves: [],
    viewsCount: 8900,
    commentsCount: 11,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_nature_3",
    userId: "traveler_osh",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoylikes.mp4",
    coverURL: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80",
    caption: "Красота Кыргызстана с квадрокоптера 4K 🏔️ Иссык-Куль, Памир и Сулайман-Тоо! #kyrgyzstan #nature #drone #mountains",
    hashtags: ["kyrgyzstan", "nature", "drone", "mountains"],
    audioTitle: "🎵 Pamir Aerial Drone Ambient Lofi 🚁✨",
    likes: ["traveler_osh", "photo_kg", "reels_star", "osh_admin"],
    saves: ["traveler_osh"],
    viewsCount: 31000,
    commentsCount: 45,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_cartoon_5",
    userId: "cartoon_master",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
    coverURL: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    caption: "🐇 Мультфильм Big Buck Bunny: Приключения упитанного Кролика в сказочном лесу! 🌳✨ #cartoon #bunny #kids #funny",
    hashtags: ["cartoon", "bunny", "kids", "funny"],
    audioTitle: "🎵 Big Buck Bunny — Forest Cartoon Orchestra 🐇🌳",
    likes: ["reels_star", "photo_kg"],
    saves: ["osh_admin"],
    viewsCount: 11400,
    commentsCount: 15,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "reel_cartoon_6",
    userId: "cartoon_master",
    type: "reel",
    mediaURL: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4",
    coverURL: "https://images.unsplash.com/photo-1557683316-973673baf926?w=800&auto=format&fit=crop&q=80",
    caption: "🤖 Sci-Fi Анимация Tears of Steel: Битва гигантских роботов будущего! 🏙️⚡ #scifi #animation #robots #cinema",
    hashtags: ["scifi", "animation", "robots", "cinema"],
    audioTitle: "🎵 Sci-Fi Robots — Cyberpunk Electronic Theme 🤖⚡",
    likes: ["traveler_osh", "reels_star"],
    saves: [],
    viewsCount: 15800,
    commentsCount: 21,
    repostedFrom: null,
    repostedBy: null,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString()
  }
];

export const SEED_STORIES = [
  {
    id: "story_a4_1",
    userId: "vlad_a4",
    mediaURL: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=600&auto=format&fit=crop&q=80",
    type: "image",
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString()
  },
  {
    id: "story_cartoon_1",
    userId: "cartoon_master",
    mediaURL: "https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=800&auto=format&fit=crop&q=80",
    type: "image",
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "story_1",
    userId: "traveler_osh",
    mediaURL: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=80",
    type: "image",
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "story_2",
    userId: "photo_kg",
    mediaURL: "https://images.unsplash.com/photo-1493612276216-ee3925520721?w=600&auto=format&fit=crop&q=80",
    type: "image",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "story_3",
    userId: "reels_star",
    mediaURL: "https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80",
    type: "image",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()
  }
];

export const SEED_COMMENTS = [
  {
    id: "comment_1",
    postId: "post_1",
    userId: "osh_admin",
    text: "Невероятный кадр! Наша Сулайман-Тоо прекрасна в любое время года 👏",
    createdAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "comment_2",
    postId: "post_1",
    userId: "photo_kg",
    text: "Отличный свет поймал, Эркин! На какой объектив снимал?",
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "comment_3",
    postId: "post_2",
    userId: "traveler_osh",
    text: "Портрет шикарен! Особенно детализация костюма.",
    createdAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "comment_4",
    postId: "post_3",
    userId: "osh_admin",
    text: "Ошский плов - это бренд! 🔥 Аж слюнки потекли.",
    createdAt: new Date(Date.now() - 10 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "comment_5",
    postId: "post_3",
    userId: "reels_star",
    text: "В какой чайхане сидели? Поделитесь локацией!",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString()
  }
];

export const SEED_CONVERSATIONS = [
  {
    id: "conv_1",
    participants: ["traveler_osh", "reels_star"],
    lastMessage: "Ок, договорились, снимем коллаб завтра на Сулайман-Тоо!",
    lastMessageAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    unreadCount: {
      traveler_osh: 0,
      reels_star: 0
    }
  },
  {
    id: "conv_2",
    participants: ["osh_admin", "traveler_osh"],
    lastMessage: "Привет! Твой пост о плове попал в рекомендации. Отличная работа!",
    lastMessageAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: {
      osh_admin: 0,
      traveler_osh: 1
    }
  }
];

export const SEED_MESSAGES = [
  {
    id: "msg_1",
    conversationId: "conv_1",
    senderId: "traveler_osh",
    text: "Привет, Адинай! Видела мои новые фото с горы?",
    sharedPostId: null,
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "msg_2",
    conversationId: "conv_1",
    senderId: "reels_star",
    text: "Привет! Да, заценила! Очень крутые цвета. Давай сделаем Reels вместе?",
    sharedPostId: null,
    createdAt: new Date(Date.now() - 3.5 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "msg_3",
    conversationId: "conv_1",
    senderId: "traveler_osh",
    text: "Крутая идея! Какая тема?",
    sharedPostId: null,
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "msg_4",
    conversationId: "conv_1",
    senderId: "reels_star",
    text: "Ок, договорились, снимем коллаб завтра на Сулайман-Тоо!",
    sharedPostId: null,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "msg_5",
    conversationId: "conv_2",
    senderId: "osh_admin",
    text: "Привет! Твой пост о плове попал в рекомендации. Отличная работа!",
    sharedPostId: "post_3", // Share post_3 in chat
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString()
  }
];

export const SEED_REPORTS = [
  {
    id: "rep_1",
    reporterId: "reels_star",
    postId: "post_2",
    reason: "Недопустимый контент / спам",
    status: "pending",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString()
  }
];

export const SEED_NOTIFICATIONS = [
  {
    id: "notif_1",
    userId: "traveler_osh",
    senderId: "osh_admin",
    type: "like",
    postId: "post_1",
    read: false,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "notif_2",
    userId: "traveler_osh",
    senderId: "reels_star",
    type: "comment",
    postId: "post_3",
    commentText: "В какой чайхане сидели? Поделитесь локацией!",
    read: false,
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString()
  },
  {
    id: "notif_3",
    userId: "traveler_osh",
    senderId: "photo_kg",
    type: "follow",
    read: true,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString()
  }
];
